In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [ ]:
data = pd.read_csv("/content/drive/My Drive/DS PROJECT/train.csv", encoding = 'Latin-1')
data

          id  label                                              tweet
0          1      0   @user when a father is dysfunctional and is s...
1          2      0  @user @user thanks for #lyft credit i can't us...
2          3      0                                bihday your majesty
3          4      0  #model   i love u take with u all the time in ...
4          5      0             factsguide: society now    #motivation
...      ...    ...                                                ...
31957  31958      0  ate @user isz that youuu?Ã°ÂÂÂÃ°ÂÂÂÃ°ÂÂ...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

[31962 rows x 3 columns]

In [ ]:
data.shape

(31962, 3)

In [ ]:
X_train = data.tweet

In [ ]:
y_train = data.label

In [ ]:
data.drop(['id'],axis = 1,inplace = True)
data.shape

(31962, 2)

In [ ]:
data

       label                                              tweet
0          0   @user when a father is dysfunctional and is s...
1          0  @user @user thanks for #lyft credit i can't us...
2          0                                bihday your majesty
3          0  #model   i love u take with u all the time in ...
4          0             factsguide: society now    #motivation
...      ...                                                ...
31957      0  ate @user isz that youuu?Ã°ÂÂÂÃ°ÂÂÂÃ°ÂÂ...
31958      0    to see nina turner on the airwaves trying to...
31959      0  listening to sad songs on a monday morning otw...
31960      1  @user #sikh #temple vandalised in in #calgary,...
31961      0                   thank you @user for you follow

[31962 rows x 2 columns]

In [ ]:
#CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#creating an object for CountVectorizer
count_vector = CountVectorizer()

In [ ]:
#generate the word counts for the words in the documents
word_count = count_vector.fit(X_train) 
word_count.get_feature_names()

['00',
 '000',
 '000001',
 '001',
 '0099',
 '00am',
 '00h30',
 '00pm',
 '01',
 '0115',
 '0161',
 '01926889917',
 '02',
 '0266808099',
 '03',
 '030916',
 '03111880779',
 '033',
 '0345',
 '039',
 '04',
 '0450',
 '04pm',
 '05',
 '0506823156',
 '05pm',
 '06',
 '0606',
 '0608',
 '0609',
 '0610',
 '0612',
 '0613',
 '0616',
 '0616ã',
 '0617',
 '0618',
 '0618ã',
 '0619',
 '0620',
 '0622',
 '064',
 '07',
 '07788427999',
 '08',
 '0830',
 '09',
 '09053111156',
 '095m',
 '0k',
 '0shares',
 '0tolerancemovie',
 '0ã',
 '10',
 '100',
 '1000',
 '10003',
 '10007',
 '1000gifts',
 '1000th',
 '1000x',
 '1000ã',
 '1001',
 '10014',
 '10021',
 '10025',
 '10040',
 '100d',
 '100daysofcode',
 '100daysofpigpaintings',
 '100daysoftea',
 '100faces',
 '100happydays',
 '100happydaysã',
 '100happysongs',
 '100k',
 '100ml',
 '100ã',
 '101',
 '1014',
 '101dalmatians',
 '101daysofsmiles',
 '101ã',
 '1024x589',
 '10353',
 '104',
 '105',
 '105kg',
 '106',
 '107',
 '1070',
 '1080',
 '109',
 '10a',
 '10am',
 '10days',
 '10hrs',
 '10k',
 '10kday',
 '10kms',
 '10m',
 '10meses',
 '10miler',
 '10millionmiler',
 '10min',
 '10minutes',
 '10minutestogo',
 '10moreyrs',
 '10pm',
 '10ppm',
 '10s',
 '10th',
 '10vouchers',
 '10x',
 '10yr',
 '11',
 '110',
 '11192016',
 '112',
 '113days',
 '114',
 '115',
 '116000',
 '1162',
 '117',
 '118',
 '1180',
 '119',
 '11am',
 '11daystogo',
 '11inchlatcock',
 '11j',
 '11millionsubs',
 '11pm',
 '11pt',
 '11th',
 '11thmonthsary',
 '12',
 '120',
 '1200',
 '1200custom',
 '1200d',
 '1230',
 '1235',
 '123rd',
 '1240',
 '125',
 '1250',
 '12500',
 '1270',
 '127tn',
 '128',
 '1280',
 '12952',
 '12daystoolong',
 '12june',
 '12k',
 '12mill',
 '12minm',
 '12months',
 '12pm',
 '12pt',
 '12th',
 '12weeksofexerciseã',
 '12yrs',
 '13',
 '1300',
 '13479',
 '1350',
 '13615',
 '13671370',
 '139',
 '13am',
 '13cabs',
 '13daystogo',
 '13hrs',
 '13percent',
 '13th',
 '13thdocumentary',
 '13yr',
 '14',
 '140',
 '1400',
 '14000',
 '1418now',
 '144',
 '14509',
 '146',
 '1465403833',
 '1465483507',
 '1465491180',
 '1465518559',
 '1465521171',
 '1465539660',
 '1465594163',
 '1465615732',
 '1465624891',
 '1465668067',
 '1465668788',
 '1465729992',
 '1465748450',
 '1465876849',
 '1466015800',
 '1466047260',
 '1466117543',
 '1466130990',
 '1466131487',
 '1466146848',
 '1466161951',
 '1466254855',
 '1466257480',
 '1466278135',
 '1466316751',
 '1466319641',
 '1466323241',
 '1466356358',
 '1466357796',
 '1466360435',
 '1466388736',
 '147',
 '149',
 '14days',
 '14june',
 '14th',
 '14weeks',
 '14ã',
 '15',
 '150',
 '1500',
 '15000',
 '150202',
 '150kg',
 '151',
 '154',
 '157',
 '158lbsã',
 '1592',
 '15am',
 '15egsc',
 '15july',
 '15k',
 '15pm',
 '15th',
 '15ã',
 '16',
 '160',
 '16026',
 '160327',
 '160613',
 '160618',
 '160619ã',
 '161',
 '161618',
 '162',
 '1621',
 '1629ã³â¾â',
 '165',
 '168',
 '16gb',
 '16h',
 '16june',
 '16juni',
 '16mm',
 '16th',
 '16thjune',
 '16y',
 '16years',
 '16yrs',
 '17',
 '170',
 '171',
 '171m',
 '174',
 '1744',
 '175',
 '178',
 '17june',
 '17th',
 '17weeks',
 '17yo',
 '18',
 '1800s',
 '1803',
 '182',
 '1848',
 '1855',
 '1861',
 '187',
 '1882',
 '18hourheels',
 '18june2016',
 '18mm',
 '18mth',
 '18th',
 '18thã',
 '18yearsold',
 '18ã',
 '19',
 '190k',
 '1926',
 '192chandragupta',
 '1930',
 '1930s',
 '1933',
 '1940',
 '1942',
 '195',
 '1950',
 '1956',
 '195daystogo',
 '1960',
 '1960s',
 '1962',
 '1963',
 '1964',
 '1966',
 '1967',
 '1968',
 '1975',
 '1976',
 '1977',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1984',
 '1987',
 '1989',
 '1992',
 '1994',
 '1995',
 '1995ã',
 '1996',
 '1997',
 '1998',
 '1999',
 '19days',
 '19th',
 '19yr',
 '19ã',
 '1a',
 '1afilm',
 '1am',
 '1aã',
 '1b',
 '1d',
 '1dad',
 '1day',
 '1dayleft',
 '1dbetweenus',
 '1dfana',
 '1dspecials',
 '1ea',
 '1gabba',
 '1gaã',
 '1gã',
 '1hitmusicstation',
 '1hr',
 '1in5',
 '1k',
 '1l',
 '1linewed',
 '1love',
 '1m25s',
 '1monthtogo',
 '1more',
 '1night',
 '1of',
 '1pm',
 '1pun',
 '1q',
 '1s',
 '1st',
 '1stactivity',
 '1stammendment',
 '1stgame',
 '1struggle',
 '1stsoloalbum',
 '1stsoloalbumleejonghyun',
 '1sttime',
 '1stvoteever',
 '1week3days',
 '1weektogo',
 '1world',
 '1year',
 '1year3monthsã',
 '1yearagã',
 '1yf',
 '1yr',
 '1ã',
 '20',
 '200',
 '2000',
 '2000steps',
 '2001',
 '2002',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '200k',
 '200m',
 '200yrs',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '20141023',
 '2015',
 '2016',
 '20160611',
 '20160612',
 '20160619',
 '2016election',
 '2016highlights',
 '2016in4words',
 '2016in4wordsã',
 '2016in4wordã',
 '2016in4worlds',
 '2016in4ã',
 '2016inã',
 '2016iã',
 '2016neotour',
 '2016release',
 '2016ã',
 '2017',
 '2017fail',
 '2017in3words',
 '2017in3wordsã',
 '2017pleasecome',
 '2018',
 '201ã',
 '2020',
 '2023',
 '2026',
 '2077',
 '20days',
 '20flaglerstreet',
 '20hrs',
 '20k',
 '20km',
 '20likes',
 '20million',
 '20mins',
 '20monthsold',
 '20poundnote',
 '20th',
 '20yrs',
 '20ã',
 '21',
 '2100',
 '214lbs',
 '218',
 '21century',
 '21ceã',
 '21hrlater',
 '21m49s',
 '21pilots',
 '21st',
 '21thbihday',
 '21yrs',
 '21ã',
 '22',
 '220',
 '22092016',
 '220skinnywraps',
 '225',
 '226',
 '226m',
 '228',
 '229',
 '229lbs',
 '22drivers',
 '22g',
 '22nd',
 '22ndbihday',
 '22ndjuly2016',
 '22ã',
 '23',
 '230',
 '2311',
 '23181573',
 '233',
 '235',
 '238',
 '23m',
 '23rd',
 '23years',
 '23ã',
 '24',
 '240',
 '241ornothing',
 '249',
 '24h',
 '24hoursinpolice',
 '24hrs',
 '24lm',
 '24th',
 '24yoder',
 '24ã',
 '25',
 '250',
 '250days',
 '257',
 '25mm',
 '25th',
 '25years',
 '25yearsstrong',
 '26',
 '260',
 '265',
 '26551',
 '268',
 '26candles',
 '26m',
 '26th',
 '27',
 '2700',
 '2720',
 '27th',
 '28',
 '280',
 '2800',
 '2840',
 '2850',
 '289',
 '28jun',
 '28lbsdown',
 '28th',
 '28weekspregnant',
 '28yos',
 '28ã',
 '29',
 '2900',
 '294',
 '294b',
 '298',
 '29am',
 '29hrs',
 '29may',
 '29th',
 '29thwithrisp',
 '29weeks',
 '2_pearls',
 '2a',
 '2amp',
 '2b',
 '2bcagency',
 '2bcã',
 '2bear',
 '2c',
 '2day',
 '2dayd',
 '2days',
 '2daysleft',
 '2do',
 '2fa',
 '2have2',
 '2hear',
 '2horrific',
 '2k',
 '2k15',
 '2k16',
 '2k16ã',
 '2keep',
 '2kfollowers',
 '2lb',
 '2leaps',
 '2likes',
 '2line',
 '2m',
 '2miles',
 '2mill',
 '2minutebeachclean',
 '2month',
 '2more',
 '2moro',
 '2mororider',
 '2morro',
 '2morrow',
 '2muchpower',
 '2nd',
 '2ndamendment',
 '2ne1',
 '2night',
 '2nite',
 '2nites',
 '2of2',
 '2off',
 '2our',
 '2outs',
 '2pac',
 '2play',
 '2pm',
 '2q',
 '2raise',
 '2s',
 '2sharia',
 '2sisters',
 '2stand',
 '2tell',
 '2the',
 '2think',
 '2trains',
 '2weeks',
 '2weekstoday',
 '2wks',
 '2x04',
 '2year',
 '2years',
 '2yearsã',
 '2yo',
 '2young',
 '2yr',
 '2ã',
 '30',
 '300',
 '3000',
 '300dayshappy',
 '300k',
 '300th',
 '301',
 '302',
 '303gallery',
 '30am',
 '30bihday',
 '30daylifechallenge',
 '30daysofbagrrys',
 '30daysofcreation',
 '30dayswild',
 '30for30',
 '30isthenew20',
 '30pm',
 '30pmet',
 '30s',
 '30stm',
 '30th',
 '30thã',
 '30tomorrow',
 '30ã',
 '31',
 '3102',
 '316xnfg',
 '318',
 '319',
 '31st',
 '31today',
 '32',
 '321',
 '327',
 '32minutes',
 '33',
 '330',
 '3311',
 '333',
 '33333',
 '3334',
 '335',
 '336lbs',
 '33hr',
 '33th',
 '33weeks',
 '33ã',
 '34',
 '3425',
 '349',
 '34th',
 '35',
 '350',
 '350s',
 '357',
 '35mins',
 '35th',
 '36',
 '360',
 '3600',
 '360lifestyle',
 '360video',
 '363',
 '3640',
 '365',
 '365black',
 '365bã',
 '366',
 '366days',
 '366photos2016',
 '36b',
 '36weeks',
 '37',
 '375b',
 '37days',
 '38',
 '3818',
 '386',
 '3866',
 '38billion',
 '39',
 '391',
 '3aday',
 '3am',
 '3athlonlife',
 '3b',
 '3become4',
 '3bookstogo',
 '3bã',
 '3d',
 '3days',
 '3daysleft',
 '3dcommerce',
 '3ddesign',
 '3dhã',
 '3dmodelling',
 '3dprint',
 '3dprinting',
 '3fridaynights',
 '3g',
 '3gswing',
 '3hrs',
 '3k',
 '3lines',
 '3m',
 '3mi',
 '3months',
 '3pm',
 '3qw',
 '3rd',
 '3rdplace',
 '3rdã',
 '3rs',
 '3thousand',
 '3to6',
 '3x',
 '3yearold',
 '3years',
 '3yearsinarow',
 '3yearswithbts',
 '3yr',
 '40',
 '400',
 '4000',
 '404',
 '40404',
 '405',
 '407',
 '40pm',
 '40points',
 '40s',
 '40th',
 '40years',
 '41',
 '410',
 '4140',
 '419b',
 '41s',
 '42',
 '420',
 '4200',
 '4256px',
 '42b',
 '42k',
 '42ndstreet',
 '43',
 '4300',
 '4330',
 '435',
 '43hr',
 '44',
 '4440',
 '44years',
 '45',
 '45am',
 '45pm',
 '45th',
 '45y',
 '46',
 '4601674919',
 '47',
 '475',
 '4798',
 '47days',
 '48',
 '484',
 '48hrs',
 '48th',
 '48thweeksary',
 '49',
 '49287',
 '49ers',
 '49irls',
 '4am',
 '4b',
 '4bã',
 '4c',
 '4daystogokianandjc',
 '4give',
 '4glte',
 '4hr',
 '4k',
 '4likeã',
 '4m',
 '4mansquad',
 '4maps',
 '4minute',
 '4minuteforever',
 '4minutepleasestaytogether',
 '4minutepleasestaywithus',
 '4o4o4',
 '4pm',
 '4practice',
 '4rm',
 '4s',
 '4sho',
 '4spreading',
 '4st',
 '4stone11lb',
 '4th',
 '4thimpact',
 '4thplacer',
 '4u',
 '4ver',
 '4way',
 '4wd',
 '4weeks',
 '4y',
 '4yearsofpkdh',
 '4ã',
 '50',
 '500',
 '5000',
 '503',
 '506iv',
 '50900',
 '50am',
 '50and',
 '50days',
 '50dead',
 '50mhz',
 '50mm',
 '50p',
 '50reasonstolovepkn',
 '50sborn',
 '50th',
 '51',
 '510',
 '52',
 '52b',
 '53',
 '530show',
 '53injured',
 '54',
 '541',
 '549',
 '55',
 '550',
 '55am',
 '55kg',
 '55th',
 '56',
 '560',
 '561',
 '564943',
 '566',
 '57',
 '5739',
 '5795',
 '58',
 '58000',
 '58days',
 '59',
 '59000',
 '59am',
 '5am',
 '5b',
 '5bn',
 '5days',
 '5h',
 '5hardweeksuntilsummerã',
 '5hrs',
 '5k',
 '5kaday',
 '5kcal',
 '5kg',
 '5lbs',
 '5min',
 '5minutes',
 '5mm',
 '5p',
 '5pm',
 '5ps',
 '5secondsofsummerconce',
 '5sos',
 '5sosmannheim',
 '5star',
 '5teams',
 '5th',
 '5thfloor',
 '5v',
 '5wordtrumplethinskin',
 '5x11',
 '5years',
 '5yo',
 '5yr',
 '5yrs',
 '5ã',
 '60',
 '600',
 '600k',
 '600x600',
 '603',
 '6071',
 '608',
 '60mill',
 '60mins',
 '60minutes',
 '60pa',
 '60s',
 '61',
 '610',
 '613',
 '614',
 '614day',
 '615',
 '6150',
 '616dayã',
 '61716',
 '6175',
 '62',
 '620',
 '625',
 '63',
 '638',
 '6380',
 '64',
 '641',
 '64ã',
 '65',
 '650',
 '65th',
 '66',
 '666',
 '67',
 '67th',
 '68th',
 '69',
 '692',
 '69p',
 '6am',
 '6b',
 '6balls',
 '6bã',
 '6days',
 '6hrsã',
 '6kgtooheavytorunwiththo',
 '6p',
 '6pcs',
 '6pm',
 '6th',
 '6thclasses',
 '6thcousin',
 '6weeks',
 '6yearslater',
 '6yearsofpll',
 '6yearswithinfinite',
 '6yo',
 '6yrs',
 '6ã',
 '70',
 '700',
 '7000',
 '700d',
 '702',
 '7040',
 '7044',
 '709',
 '70s',
 '70thannualtonyawards',
 '71',
 '711',
 '712',
 '713',
 '714',
 '715',
 '7150',
 '7190',
 '71st',
 '72',
 '720p',
 '727',
 '73',
 '74',
 '7400',
 '7468',
 '74m',
 '75',
 '7500',
 '76',
 '760',
 '763',
 ...]

In [ ]:
#Converting to a array
array = word_count.transform(X_train).toarray()
array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
#Converting the array into a dataframe
df = pd.DataFrame(array,columns = word_count.get_feature_names())
df

       00  000  000001  001  0099  00am  ...  â¾ã³â¾â  ãªâ  ãªâ²â  ãªâµâ  ã²â  ã³â¾â
0       0    0       0    0     0     0  ...        0    0      0      0    0      0
1       0    0       0    0     0     0  ...        0    0      0      0    0      0
2       0    0       0    0     0     0  ...        0    0      0      0    0      0
3       0    0       0    0     0     0  ...        0    0      0      0    0      0
4       0    0       0    0     0     0  ...        0    0      0      0    0      0
...    ..  ...     ...  ...   ...   ...  ...      ...  ...    ...    ...  ...    ...
31957   0    0       0    0     0     0  ...        0    0      0      0    0      0
31958   0    0       0    0     0     0  ...        0    0      0      0    0      0
31959   0    0       0    0     0     0  ...        0    0      0      0    0      0
31960   0    0       0    0     0     0  ...        0    0      0      0    0      0
31961   0    0       0    0     0     0  ...        0    0      0      0    0      0

[31962 rows x 41074 columns]

In [ ]:
#TFIDF Vectorizer

#Import TFIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#Initialize an object for the TFIDF Vectorizer
tfidf_vect = TfidfVectorizer()

In [ ]:
#apply the tfidf to the data(X_train)
X_train_transformed = tfidf_vect.fit_transform(X_train)
X_train_transformed

<31962x41074 sparse matrix of type '<class 'numpy.float64'>'
	with 367513 stored elements in Compressed Sparse Row format>

In [ ]:
#Feature Names
tfidf_vect.get_feature_names()

['00',
 '000',
 '000001',
 '001',
 '0099',
 '00am',
 '00h30',
 '00pm',
 '01',
 '0115',
 '0161',
 '01926889917',
 '02',
 '0266808099',
 '03',
 '030916',
 '03111880779',
 '033',
 '0345',
 '039',
 '04',
 '0450',
 '04pm',
 '05',
 '0506823156',
 '05pm',
 '06',
 '0606',
 '0608',
 '0609',
 '0610',
 '0612',
 '0613',
 '0616',
 '0616ã',
 '0617',
 '0618',
 '0618ã',
 '0619',
 '0620',
 '0622',
 '064',
 '07',
 '07788427999',
 '08',
 '0830',
 '09',
 '09053111156',
 '095m',
 '0k',
 '0shares',
 '0tolerancemovie',
 '0ã',
 '10',
 '100',
 '1000',
 '10003',
 '10007',
 '1000gifts',
 '1000th',
 '1000x',
 '1000ã',
 '1001',
 '10014',
 '10021',
 '10025',
 '10040',
 '100d',
 '100daysofcode',
 '100daysofpigpaintings',
 '100daysoftea',
 '100faces',
 '100happydays',
 '100happydaysã',
 '100happysongs',
 '100k',
 '100ml',
 '100ã',
 '101',
 '1014',
 '101dalmatians',
 '101daysofsmiles',
 '101ã',
 '1024x589',
 '10353',
 '104',
 '105',
 '105kg',
 '106',
 '107',
 '1070',
 '1080',
 '109',
 '10a',
 '10am',
 '10days',
 '10hrs',
 '10k',
 '10kday',
 '10kms',
 '10m',
 '10meses',
 '10miler',
 '10millionmiler',
 '10min',
 '10minutes',
 '10minutestogo',
 '10moreyrs',
 '10pm',
 '10ppm',
 '10s',
 '10th',
 '10vouchers',
 '10x',
 '10yr',
 '11',
 '110',
 '11192016',
 '112',
 '113days',
 '114',
 '115',
 '116000',
 '1162',
 '117',
 '118',
 '1180',
 '119',
 '11am',
 '11daystogo',
 '11inchlatcock',
 '11j',
 '11millionsubs',
 '11pm',
 '11pt',
 '11th',
 '11thmonthsary',
 '12',
 '120',
 '1200',
 '1200custom',
 '1200d',
 '1230',
 '1235',
 '123rd',
 '1240',
 '125',
 '1250',
 '12500',
 '1270',
 '127tn',
 '128',
 '1280',
 '12952',
 '12daystoolong',
 '12june',
 '12k',
 '12mill',
 '12minm',
 '12months',
 '12pm',
 '12pt',
 '12th',
 '12weeksofexerciseã',
 '12yrs',
 '13',
 '1300',
 '13479',
 '1350',
 '13615',
 '13671370',
 '139',
 '13am',
 '13cabs',
 '13daystogo',
 '13hrs',
 '13percent',
 '13th',
 '13thdocumentary',
 '13yr',
 '14',
 '140',
 '1400',
 '14000',
 '1418now',
 '144',
 '14509',
 '146',
 '1465403833',
 '1465483507',
 '1465491180',
 '1465518559',
 '1465521171',
 '1465539660',
 '1465594163',
 '1465615732',
 '1465624891',
 '1465668067',
 '1465668788',
 '1465729992',
 '1465748450',
 '1465876849',
 '1466015800',
 '1466047260',
 '1466117543',
 '1466130990',
 '1466131487',
 '1466146848',
 '1466161951',
 '1466254855',
 '1466257480',
 '1466278135',
 '1466316751',
 '1466319641',
 '1466323241',
 '1466356358',
 '1466357796',
 '1466360435',
 '1466388736',
 '147',
 '149',
 '14days',
 '14june',
 '14th',
 '14weeks',
 '14ã',
 '15',
 '150',
 '1500',
 '15000',
 '150202',
 '150kg',
 '151',
 '154',
 '157',
 '158lbsã',
 '1592',
 '15am',
 '15egsc',
 '15july',
 '15k',
 '15pm',
 '15th',
 '15ã',
 '16',
 '160',
 '16026',
 '160327',
 '160613',
 '160618',
 '160619ã',
 '161',
 '161618',
 '162',
 '1621',
 '1629ã³â¾â',
 '165',
 '168',
 '16gb',
 '16h',
 '16june',
 '16juni',
 '16mm',
 '16th',
 '16thjune',
 '16y',
 '16years',
 '16yrs',
 '17',
 '170',
 '171',
 '171m',
 '174',
 '1744',
 '175',
 '178',
 '17june',
 '17th',
 '17weeks',
 '17yo',
 '18',
 '1800s',
 '1803',
 '182',
 '1848',
 '1855',
 '1861',
 '187',
 '1882',
 '18hourheels',
 '18june2016',
 '18mm',
 '18mth',
 '18th',
 '18thã',
 '18yearsold',
 '18ã',
 '19',
 '190k',
 '1926',
 '192chandragupta',
 '1930',
 '1930s',
 '1933',
 '1940',
 '1942',
 '195',
 '1950',
 '1956',
 '195daystogo',
 '1960',
 '1960s',
 '1962',
 '1963',
 '1964',
 '1966',
 '1967',
 '1968',
 '1975',
 '1976',
 '1977',
 '1980s',
 '1981',
 '1982',
 '1983',
 '1984',
 '1987',
 '1989',
 '1992',
 '1994',
 '1995',
 '1995ã',
 '1996',
 '1997',
 '1998',
 '1999',
 '19days',
 '19th',
 '19yr',
 '19ã',
 '1a',
 '1afilm',
 '1am',
 '1aã',
 '1b',
 '1d',
 '1dad',
 '1day',
 '1dayleft',
 '1dbetweenus',
 '1dfana',
 '1dspecials',
 '1ea',
 '1gabba',
 '1gaã',
 '1gã',
 '1hitmusicstation',
 '1hr',
 '1in5',
 '1k',
 '1l',
 '1linewed',
 '1love',
 '1m25s',
 '1monthtogo',
 '1more',
 '1night',
 '1of',
 '1pm',
 '1pun',
 '1q',
 '1s',
 '1st',
 '1stactivity',
 '1stammendment',
 '1stgame',
 '1struggle',
 '1stsoloalbum',
 '1stsoloalbumleejonghyun',
 '1sttime',
 '1stvoteever',
 '1week3days',
 '1weektogo',
 '1world',
 '1year',
 '1year3monthsã',
 '1yearagã',
 '1yf',
 '1yr',
 '1ã',
 '20',
 '200',
 '2000',
 '2000steps',
 '2001',
 '2002',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '200k',
 '200m',
 '200yrs',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '20141023',
 '2015',
 '2016',
 '20160611',
 '20160612',
 '20160619',
 '2016election',
 '2016highlights',
 '2016in4words',
 '2016in4wordsã',
 '2016in4wordã',
 '2016in4worlds',
 '2016in4ã',
 '2016inã',
 '2016iã',
 '2016neotour',
 '2016release',
 '2016ã',
 '2017',
 '2017fail',
 '2017in3words',
 '2017in3wordsã',
 '2017pleasecome',
 '2018',
 '201ã',
 '2020',
 '2023',
 '2026',
 '2077',
 '20days',
 '20flaglerstreet',
 '20hrs',
 '20k',
 '20km',
 '20likes',
 '20million',
 '20mins',
 '20monthsold',
 '20poundnote',
 '20th',
 '20yrs',
 '20ã',
 '21',
 '2100',
 '214lbs',
 '218',
 '21century',
 '21ceã',
 '21hrlater',
 '21m49s',
 '21pilots',
 '21st',
 '21thbihday',
 '21yrs',
 '21ã',
 '22',
 '220',
 '22092016',
 '220skinnywraps',
 '225',
 '226',
 '226m',
 '228',
 '229',
 '229lbs',
 '22drivers',
 '22g',
 '22nd',
 '22ndbihday',
 '22ndjuly2016',
 '22ã',
 '23',
 '230',
 '2311',
 '23181573',
 '233',
 '235',
 '238',
 '23m',
 '23rd',
 '23years',
 '23ã',
 '24',
 '240',
 '241ornothing',
 '249',
 '24h',
 '24hoursinpolice',
 '24hrs',
 '24lm',
 '24th',
 '24yoder',
 '24ã',
 '25',
 '250',
 '250days',
 '257',
 '25mm',
 '25th',
 '25years',
 '25yearsstrong',
 '26',
 '260',
 '265',
 '26551',
 '268',
 '26candles',
 '26m',
 '26th',
 '27',
 '2700',
 '2720',
 '27th',
 '28',
 '280',
 '2800',
 '2840',
 '2850',
 '289',
 '28jun',
 '28lbsdown',
 '28th',
 '28weekspregnant',
 '28yos',
 '28ã',
 '29',
 '2900',
 '294',
 '294b',
 '298',
 '29am',
 '29hrs',
 '29may',
 '29th',
 '29thwithrisp',
 '29weeks',
 '2_pearls',
 '2a',
 '2amp',
 '2b',
 '2bcagency',
 '2bcã',
 '2bear',
 '2c',
 '2day',
 '2dayd',
 '2days',
 '2daysleft',
 '2do',
 '2fa',
 '2have2',
 '2hear',
 '2horrific',
 '2k',
 '2k15',
 '2k16',
 '2k16ã',
 '2keep',
 '2kfollowers',
 '2lb',
 '2leaps',
 '2likes',
 '2line',
 '2m',
 '2miles',
 '2mill',
 '2minutebeachclean',
 '2month',
 '2more',
 '2moro',
 '2mororider',
 '2morro',
 '2morrow',
 '2muchpower',
 '2nd',
 '2ndamendment',
 '2ne1',
 '2night',
 '2nite',
 '2nites',
 '2of2',
 '2off',
 '2our',
 '2outs',
 '2pac',
 '2play',
 '2pm',
 '2q',
 '2raise',
 '2s',
 '2sharia',
 '2sisters',
 '2stand',
 '2tell',
 '2the',
 '2think',
 '2trains',
 '2weeks',
 '2weekstoday',
 '2wks',
 '2x04',
 '2year',
 '2years',
 '2yearsã',
 '2yo',
 '2young',
 '2yr',
 '2ã',
 '30',
 '300',
 '3000',
 '300dayshappy',
 '300k',
 '300th',
 '301',
 '302',
 '303gallery',
 '30am',
 '30bihday',
 '30daylifechallenge',
 '30daysofbagrrys',
 '30daysofcreation',
 '30dayswild',
 '30for30',
 '30isthenew20',
 '30pm',
 '30pmet',
 '30s',
 '30stm',
 '30th',
 '30thã',
 '30tomorrow',
 '30ã',
 '31',
 '3102',
 '316xnfg',
 '318',
 '319',
 '31st',
 '31today',
 '32',
 '321',
 '327',
 '32minutes',
 '33',
 '330',
 '3311',
 '333',
 '33333',
 '3334',
 '335',
 '336lbs',
 '33hr',
 '33th',
 '33weeks',
 '33ã',
 '34',
 '3425',
 '349',
 '34th',
 '35',
 '350',
 '350s',
 '357',
 '35mins',
 '35th',
 '36',
 '360',
 '3600',
 '360lifestyle',
 '360video',
 '363',
 '3640',
 '365',
 '365black',
 '365bã',
 '366',
 '366days',
 '366photos2016',
 '36b',
 '36weeks',
 '37',
 '375b',
 '37days',
 '38',
 '3818',
 '386',
 '3866',
 '38billion',
 '39',
 '391',
 '3aday',
 '3am',
 '3athlonlife',
 '3b',
 '3become4',
 '3bookstogo',
 '3bã',
 '3d',
 '3days',
 '3daysleft',
 '3dcommerce',
 '3ddesign',
 '3dhã',
 '3dmodelling',
 '3dprint',
 '3dprinting',
 '3fridaynights',
 '3g',
 '3gswing',
 '3hrs',
 '3k',
 '3lines',
 '3m',
 '3mi',
 '3months',
 '3pm',
 '3qw',
 '3rd',
 '3rdplace',
 '3rdã',
 '3rs',
 '3thousand',
 '3to6',
 '3x',
 '3yearold',
 '3years',
 '3yearsinarow',
 '3yearswithbts',
 '3yr',
 '40',
 '400',
 '4000',
 '404',
 '40404',
 '405',
 '407',
 '40pm',
 '40points',
 '40s',
 '40th',
 '40years',
 '41',
 '410',
 '4140',
 '419b',
 '41s',
 '42',
 '420',
 '4200',
 '4256px',
 '42b',
 '42k',
 '42ndstreet',
 '43',
 '4300',
 '4330',
 '435',
 '43hr',
 '44',
 '4440',
 '44years',
 '45',
 '45am',
 '45pm',
 '45th',
 '45y',
 '46',
 '4601674919',
 '47',
 '475',
 '4798',
 '47days',
 '48',
 '484',
 '48hrs',
 '48th',
 '48thweeksary',
 '49',
 '49287',
 '49ers',
 '49irls',
 '4am',
 '4b',
 '4bã',
 '4c',
 '4daystogokianandjc',
 '4give',
 '4glte',
 '4hr',
 '4k',
 '4likeã',
 '4m',
 '4mansquad',
 '4maps',
 '4minute',
 '4minuteforever',
 '4minutepleasestaytogether',
 '4minutepleasestaywithus',
 '4o4o4',
 '4pm',
 '4practice',
 '4rm',
 '4s',
 '4sho',
 '4spreading',
 '4st',
 '4stone11lb',
 '4th',
 '4thimpact',
 '4thplacer',
 '4u',
 '4ver',
 '4way',
 '4wd',
 '4weeks',
 '4y',
 '4yearsofpkdh',
 '4ã',
 '50',
 '500',
 '5000',
 '503',
 '506iv',
 '50900',
 '50am',
 '50and',
 '50days',
 '50dead',
 '50mhz',
 '50mm',
 '50p',
 '50reasonstolovepkn',
 '50sborn',
 '50th',
 '51',
 '510',
 '52',
 '52b',
 '53',
 '530show',
 '53injured',
 '54',
 '541',
 '549',
 '55',
 '550',
 '55am',
 '55kg',
 '55th',
 '56',
 '560',
 '561',
 '564943',
 '566',
 '57',
 '5739',
 '5795',
 '58',
 '58000',
 '58days',
 '59',
 '59000',
 '59am',
 '5am',
 '5b',
 '5bn',
 '5days',
 '5h',
 '5hardweeksuntilsummerã',
 '5hrs',
 '5k',
 '5kaday',
 '5kcal',
 '5kg',
 '5lbs',
 '5min',
 '5minutes',
 '5mm',
 '5p',
 '5pm',
 '5ps',
 '5secondsofsummerconce',
 '5sos',
 '5sosmannheim',
 '5star',
 '5teams',
 '5th',
 '5thfloor',
 '5v',
 '5wordtrumplethinskin',
 '5x11',
 '5years',
 '5yo',
 '5yr',
 '5yrs',
 '5ã',
 '60',
 '600',
 '600k',
 '600x600',
 '603',
 '6071',
 '608',
 '60mill',
 '60mins',
 '60minutes',
 '60pa',
 '60s',
 '61',
 '610',
 '613',
 '614',
 '614day',
 '615',
 '6150',
 '616dayã',
 '61716',
 '6175',
 '62',
 '620',
 '625',
 '63',
 '638',
 '6380',
 '64',
 '641',
 '64ã',
 '65',
 '650',
 '65th',
 '66',
 '666',
 '67',
 '67th',
 '68th',
 '69',
 '692',
 '69p',
 '6am',
 '6b',
 '6balls',
 '6bã',
 '6days',
 '6hrsã',
 '6kgtooheavytorunwiththo',
 '6p',
 '6pcs',
 '6pm',
 '6th',
 '6thclasses',
 '6thcousin',
 '6weeks',
 '6yearslater',
 '6yearsofpll',
 '6yearswithinfinite',
 '6yo',
 '6yrs',
 '6ã',
 '70',
 '700',
 '7000',
 '700d',
 '702',
 '7040',
 '7044',
 '709',
 '70s',
 '70thannualtonyawards',
 '71',
 '711',
 '712',
 '713',
 '714',
 '715',
 '7150',
 '7190',
 '71st',
 '72',
 '720p',
 '727',
 '73',
 '74',
 '7400',
 '7468',
 '74m',
 '75',
 '7500',
 '76',
 '760',
 '763',
 ...]

In [ ]:
#Position of the words in the sparse matrix
tfidf_vect.vocabulary_

{'user': 38194,
 'when': 39560,
 'father': 12983,
 'is': 18972,
 'dysfunctional': 11372,
 'and': 2385,
 'so': 33428,
 'selfish': 32089,
 'he': 16642,
 'drags': 11050,
 'his': 17080,
 'kids': 20139,
 'into': 18812,
 'dysfunction': 11371,
 'run': 31219,
 'thanks': 35995,
 'for': 13944,
 'lyft': 22194,
 'credit': 8969,
 'can': 6485,
 'use': 38185,
 'cause': 6858,
 'they': 36327,
 'don': 10839,
 'offer': 26124,
 'wheelchair': 39554,
 'vans': 38336,
 'in': 18243,
 'pdx': 27338,
 'disapointed': 10458,
 'getthanked': 14991,
 'bihday': 4714,
 'your': 40741,
 'majesty': 22404,
 'model': 23778,
 'love': 21850,
 'take': 35424,
 'with': 39942,
 'all': 2000,
 'the': 36042,
 'time': 36597,
 'urã': 38168,
 'factsguide': 12746,
 'society': 33483,
 'now': 25841,
 'motivation': 24083,
 'huge': 17584,
 'fan': 12861,
 'fare': 12895,
 'big': 4652,
 'talking': 35463,
 'before': 4213,
 'leave': 20905,
 'chaos': 7114,
 'pay': 27279,
 'disputes': 10578,
 'get': 14961,
 'there': 36254,
 'allshowandnogo': 2080,
 'camping': 6470,
 'tomorrow': 36821,
 'dannyã': 9529,
 'next': 25229,
 'school': 31763,
 'year': 40543,
 'exams': 12438,
 'think': 36361,
 'about': 1252,
 'that': 36025,
 'hate': 16531,
 'imagine': 18110,
 'actorslife': 1424,
 'revolutionschool': 30630,
 'girl': 15112,
 'we': 39157,
 'won': 40067,
 'land': 20629,
 'allin': 2048,
 'cavs': 6871,
 'champions': 7073,
 'cleveland': 7737,
 'clevelandcavaliers': 7738,
 'welcome': 39358,
 'here': 16882,
 'it': 19082,
 'gr8': 15656,
 'ireland': 18935,
 'consumer': 8468,
 'price': 28804,
 'index': 18325,
 'mom': 23835,
 'climbed': 7770,
 'from': 14326,
 'previous': 28797,
 'to': 36730,
 'may': 22908,
 'blog': 5098,
 'silver': 32831,
 'gold': 15388,
 'forex': 13984,
 'are': 2820,
 'orlando': 26594,
 'standwithorlando': 34163,
 'pulseshooting': 29222,
 'orlandoshooting': 26606,
 'biggerproblems': 4677,
 'heabreaking': 16648,
 'values': 38303,
 'see': 31999,
 'my': 24466,
 'daddy': 9371,
 'today': 36744,
 '80days': 1035,
 'gettingfed': 14999,
 'cnn': 7875,
 'calls': 6404,
 'michigan': 23358,
 'middle': 23382,
 'build': 6072,
 'wall': 38921,
 'chant': 7111,
 'tcot': 35621,
 'no': 25460,
 'comment': 8146,
 'australia': 3263,
 'opkillingbay': 26479,
 'seashepherd': 31932,
 'helpcovedolphins': 16833,
 'thecove': 36097,
 'ouch': 26672,
 'junior': 19752,
 'angryã': 2448,
 'got7': 15597,
 'yugyoem': 40816,
 'omg': 26281,
 'am': 2202,
 'thankful': 35986,
 'having': 16589,
 'paner': 27043,
 'positive': 28447,
 'retweet': 30580,
 'if': 17893,
 'you': 40706,
 'agree': 1729,
 'its': 19107,
 'friday': 14237,
 'smiles': 33283,
 'around': 2909,
 'via': 38509,
 'ig': 17915,
 'cookies': 8570,
 'make': 22416,
 'people': 27458,
 'as': 2947,
 'know': 20326,
 'essential': 12242,
 'oils': 26188,
 'not': 25707,
 'made': 22273,
 'of': 26108,
 'chemicals': 7255,
 'euro2016': 12310,
 'blaming': 5001,
 'ha': 16154,
 'conceded': 8292,
 'goal': 15299,
 'was': 39027,
 'fat': 12972,
 'rooney': 31049,
 'who': 39685,
 'gave': 14761,
 'away': 3359,
 'free': 14156,
 'kick': 20114,
 'knowing': 20327,
 'bale': 3660,
 'hit': 17095,
 'them': 36187,
 'sad': 31351,
 'little': 21447,
 'dude': 11243,
 'badday': 3565,
 'coneofshame': 8342,
 'cats': 6839,
 'pissed': 27940,
 'funny': 14496,
 'laughs': 20773,
 'product': 28919,
 'day': 9633,
 'happy': 16400,
 'man': 22538,
 'wine': 39857,
 'tool': 36869,
 'weekend': 39289,
 'open': 26442,
 'up': 38089,
 'amp': 2327,
 'drink': 11135,
 'lumpy': 22149,
 'says': 31684,
 'prove': 29082,
 'tgif': 35958,
 'ff': 13279,
 'gamedev': 14652,
 'indiedev': 18347,
 'indiegamedev': 18350,
 'squad': 34046,
 'beautiful': 4100,
 'sign': 32794,
 'by': 6279,
 'vendor': 38416,
 '80': 1029,
 '45': 771,
 '00': 0,
 'upsideofflorida': 38135,
 'shopalyssas': 32629,
 'media': 23052,
 'pressconference': 28750,
 'antalya': 2577,
 'turkey': 37517,
 'sunday': 34906,
 'throwback': 36500,
 'had': 16177,
 'great': 15778,
 'panel': 27041,
 'on': 26292,
 'mediatization': 23056,
 'public': 29169,
 'service': 32223,
 'ica16': 17809,
 '50': 828,
 'went': 39417,
 'nightclub': 25364,
 'have': 16572,
 'good': 15441,
 'night': 25362,
 'actions': 1407,
 'means': 23024,
 'those': 36435,
 'lost': 21804,
 'their': 36160,
 'families': 12831,
 'forever': 13974,
 'rip': 30785,
 'never': 25026,
 'chance': 7080,
 'vote': 38761,
 'presidential': 28742,
 'candidate': 6517,
 'excited': 12464,
 'this': 36389,
 'cycle': 9323,
 'looks': 21747,
 'be': 4008,
 'different': 10353,
 'alohafriday': 2120,
 'does': 10737,
 'exist': 12514,
 'positivevibes': 28461,
 'hawaiian': 16596,
 'fellow': 13210,
 'nohern': 25547,
 'sadley': 31364,
 'passed': 27176,
 'tonight': 36837,
 'gawa': 14762,
 'singing': 32901,
 'cheering': 7213,
 'fire': 13476,
 'hard': 16434,
 'monday': 23877,
 'due': 11247,
 'cloudy': 7832,
 'weather': 39201,
 'disabling': 10449,
 'oxygen': 26838,
 'production': 28921,
 'goodnight': 15500,
 'badmonday': 3581,
 'unbelievable': 37843,
 '21st': 460,
 'century': 7008,
 'need': 24884,
 'something': 33595,
 'like': 21272,
 'again': 1681,
 'neverump': 25050,
 'xenophobia': 40417,
 'taylorswift1989': 35597,
 'bull': 6093,
 'will': 39805,
 'dominate': 10826,
 'direct': 10434,
 'whatever': 39518,
 'want': 38970,
 'do': 10706,
 'morning': 24022,
 'travelingram': 37142,
 'dalat': 9440,
 'ripinkylife': 30810,
 'once': 26300,
 'more': 23991,
 'only': 26357,
 'one': 26305,
 'word': 40133,
 'tells': 35815,
 'photoshop': 27756,
 'enoughisenough': 12056,
 'dontphotoshopeverything': 10895,
 'wheresallthenaturalphotos': 39590,
 'oh': 26162,
 'cedarpoint': 6934,
 'waited': 38865,
 'hours': 17477,
 'valravn': 38297,
 'line': 21362,
 'stopped': 34444,
 'working': 40164,
 'were': 39424,
 'close': 7797,
 'sunshine': 34967,
 'finally': 13409,
 'finish': 13457,
 'book': 5379,
 've': 38371,
 'been': 4189,
 'awhile': 3382,
 'bookworm': 5406,
 'ontothenextnovel': 26397,
 'yup': 40843,
 'being': 4269,
 'knicks': 20310,
 'easier': 11435,
 'just': 19764,
 'an': 2352,
 'nba': 24824,
 'playoffs': 28084,
 'roll': 30991,
 'life': 21187,
 'after': 1660,
 'social': 33461,
 'networking': 25013,
 'embrace': 11814,
 'each': 11391,
 'shares': 32414,
 'same': 31471,
 'snake': 33350,
 'â¼': 41039,
 'lovely': 21936,
 'echeveria': 11501,
 'blooms': 5140,
 'flowers': 13769,
 'grow': 15956,
 'gardening': 14704,
 'iphonesia': 18907,
 'bliss': 5080,
 'basilicabotanica': 3867,
 'amazing': 2223,
 'i_am': 17756,
 'affirmation': 1617,
 'whenever': 39563,
 'im': 18094,
 'goes': 15359,
 'wrong': 40318,
 'feeling': 13136,
 'blue': 5155,
 'illustration': 18025,
 'best': 4441,
 'pa': 26861,
 'â¼ã': 41052,
 'abc2020': 1215,
 'getting': 14996,
 'ready': 29853,
 'remove': 30327,
 'victums': 38551,
 'frm': 14317,
 'pulseclub': 29216,
 'prayfororlando': 28639,
 'her': 16870,
 'got': 15596,
 'nose': 25689,
 'job': 19515,
 'petunia': 27633,
 'off': 26115,
 'concelebrate': 8294,
 'at': 3103,
 'albanpilgrimage': 1904,
 'first': 13502,
 'let': 21043,
 'scum': 31887,
 'baggery': 3604,
 'begin': 4228,
 'thank': 35983,
 'super': 34980,
 'zpamdelacruz': 40979,
 'wedding': 39231,
 'dolores': 10817,
 'capas': 6599,
 'tarlac': 35529,
 'scourge': 31826,
 'playing': 28074,
 'baroque': 3823,
 'pieces': 27827,
 'piano': 27774,
 'beyond': 4571,
 'belief': 4298,
 'lets': 21059,
 'fight': 13331,
 'against': 1682,
 'peace': 27343,
 'fatherã': 13009,
 'mr': 24194,
 'rayos': 29793,
 'video': 38554,
 'fathers': 12990,
 'world': 40198,
 'hotvideo': 17465,
 'videos': 38562,
 'ascot': 2958,
 'times': 36613,
 'babe': 3459,
 'fashion': 12934,
 'monochrome': 23917,
 'style': 34686,
 'instahappyday': 18637,
 'selfie': 32081,
 'yolo': 40684,
 'xoxo': 40435,
 'like4like': 21275,
 'work': 40143,
 'conference': 8349,
 'right': 30739,
 'mindset': 23511,
 'leads': 20861,
 'culture': 9193,
 'development': 10223,
 'organizations': 26566,
 'christina': 7497,
 'grimmie': 15909,
 'last': 20699,
 'performance': 27519,
 'shot': 32654,
 'christinarip': 7500,
 'voice': 38731,
 'christinagrimmie': 7499,
 'dance': 9478,
 'roar': 30901,
 'preschoolers': 28724,
 'students': 34647,
 'proudã': 29079,
 'really': 29898,
 'hu': 17562,
 'feelings': 13160,
 'wife': 39767,
 'whom': 39701,
 'adore': 1530,
 'miss': 23610,
 'poland': 28247,
 'show': 32677,
 'because': 4142,
 'she': 32452,
 'surgery': 35097,
 'name': 24666,
 'bridget': 5759,
 'everything': 12392,
 'jealous': 19353,
 'chatiado': 7170,
 'celebrate': 6947,
 'every': 12369,
 'has': 16507,
 'played': 28068,
 'fatherly': 12989,
 'role': 30985,
 'sure': 35079,
 'â½ã': 41059,
 'â½': 41053,
 'hour': 17473,
 'white': 39631,
 'establishment': 12252,
 'blk': 5086,
 'folx': 13877,
 'running': 31236,
 'loving': 22036,
 'themselves': 36203,
 'promoting': 28990,
 'our': 26676,
 'greatness': 15805,
 'journey': 19618,
 'begins': 4232,
 'â³': 41011,
 'travel': 37134,
 'yeah': 40537,
 'thejourneybegins': 36169,
 'helloã': 16822,
 'luv': 22173,
 'hottweets': 17463,
 'venusexchangeã': 38436,
 'new': 25059,
 'brochures': 5862,
 'arrived': 2926,
 'how': 17504,
 'exciting': 12472,
 'aworks': 3391,
 'solutions': 33571,
 'much': 24264,
 'stuff': 34663,
 'happening': 16369,
 'florida': 13740,
 'shooting': 32624,
 'disneygatorattack': 10553,
 'two': 37645,
 'old': 26225,
 'kidã': 20152,
 'ferrari': 13246,
 'itã': 19148,
 'âªã': 40999,
 'sake': 31418,
 'championship': 7074,
 'gp': 15647,
 'clearly': 7723,
 'turning': 37528,
 'point': 28222,
 'rb': 29801,
 'mercs': 23227,
 'aced': 1356,
 'test': 35913,
 'proud': 29059,
 'seeks': 32013,
 'probe': 28891,
 'udtapunjab': 37725,
 'leak': 20869,
 'points': 28230,
 'finger': 13450,
 'amarinder': 2212,
 'aap': 1186,
 'wrapping': 40274,
 'senseaboutmaths': 32159,
 '6th': 958,
 'hey': 16927,
 'call': 6395,
 'race': 29515,
 'identity': 17862,
 'medã': 23074,
 'might': 23402,
 'shown': 32692,
 'regurgitated': 30192,
 'calling': 6401,
 'sometimes': 33605,
 'raise': 29641,
 'few': 13272,
 'brows': 5926,
 'bar': 3765,
 'golfstrengthandconditioning': 15410,
 'strong': 34612,
 'felixfoisgolf': 13192,
 'greathonour': 15797,
 'careerconvos': 6665,
 'designing': 10139,
 'innovative': 18512,
 'learning': 20890,
 'space': 33783,
 'include': 18281,
 'wateringhole': 39100,
 'cave': 6869,
 'mountaintop': 24123,
 'campfire': 6467,
 'hã': 17753,
 'altright': 2167,
 'uses': 38199,
 'insecurity': 18533,
 'lure': 22163,
 'men': 23164,
 'whitesupremacy': 39675,
 'carrying': 6740,
 'gun': 16069,
 'wouldn': 40250,
 'helped': 16834,
 'control': 8530,
 'stop': 34435,
 'black': 4918,
 'market': 22717,
 'terrorism': 35903,
 'worse': 40234,
 'power': 28550,
 'mind': 23495,
 'heal': 16683,
 'body': 5267,
 'altwaystoheal': 2170,
 'healthy': 16706,
 'woohoo': 40111,
 'over': 26768,
 'weeks': 39314,
 'go': 15293,
 'far': 12889,
 'place': 27996,
 'where': 39574,
 'family': 12834,
 'members': 23137,
 'hus': 17686,
 'rehearse': 30198,
 'music': 24383,
 'look': 21726,
 'out': 26694,
 'announcement': 2530,
 'midweek': 23395,
 'newmusic': 25160,
 'watchthisspace': 39078,
 'guitar': 16055,
 'nights': 25383,
 '8pm': 1076,
 'channel': 7106,
 'what': 39504,
 'fuss': 14542,
 'watching': 39071,
 'episodes': 12137,
 'offline': 26149,
 'very': 38472,
 'nice': 25302,
 'long': 21687,
 'snapchat': 33353,
 'redhead': 30058,
 'vermillionred': 38454,
 '15': 226,
 'things': 36356,
 'incredibly': 18308,
 'yes': 40600,
 'received': 29965,
 'acceptance': 1310,
 'letter': 21082,
 'masters': 22832,
 'back': 3520,
 'october': 26085,
 'goodtimes': 15518,
 'history': 17091,
 'daughter': 9600,
 'riding': 30722,
 'bike': 4774,
 'driveway': 11154,
 'son': 33621,
 'us': 38169,
 'while': 39605,
 'enjoy': 12029,
 'âº': 41030,
 'summeime': 34831,
 'memories': 23152,
 'station': 34228,
 'way': 39131,
 'jam': 19259,
 'done': 10856,
 'course': 8788,
 'll': 21556,
 'always': 2182,
 'hope': 17346,
 'hug': 17583,
 'but': 6221,
 'gonna': 15431,
 'happen': 16366,
 'anytime': 2640,
 'soon': 33656,
 'couple': 8776,
 'sex': 32276,
 'naked': 24655,
 'japanese': 19297,
 'girls': 15128,
 'hump': 17641,
 'humpersã': 17645,
 'edwardsville': 11608,
 'pennsylvania': 27443,
 'personalised': 27576,
 'gbp': 14809,
 '99': 1119,
 'shop': 32627,
 'cool': 8575,
 'home': 17220,
 'fun': 14451,
 'some': 33581,
 'truly': 37351,
 'sick': 32756,
 'ppl': 28571,
 'trump': 37355,
 'obama': 26009,
 'resign': 30461,
 'shootings': 32625,
 'boy': 5555,
 'years': 40548,
 'did': 10317,
 'talk': 35458,
 'change': 7090,
 'nashvilletour2016': 24722,
 'nashvilleforever': 24720,
 'eur': 12305,
 'usd': 38183,
 'clears': 7725,
 '1400': 182,
 'barrier': 3835,
 'jumps': 19712,
 'fresh': 14220,
 'week': 39282,
 'high': 16961,
 'going': 15375,
 'la': 20496,
 'friends': 14275,
 'still': 34358,
 'wrap': 40272,
 'head': 16654,
 'fact': 12739,
 'gone': 15424,
 'destroyed': 10183,
 'dis': 10445,
 'wait': 38863,
 'sta': 34091,
 'baking': 3637,
 'eyelids': 12657,
 'vigilfororlando': 38585,
 'harp': 16481,
 'clonakilty': 7793,
 'ihavenofriends': 17954,
 'someonecomewithme': 33587,
 'relax': 30242,
 'icon': 17837,
 'woman': 40026,
 'sundaymorning': 34915,
 'marilynmonroe': 22699,
 'interested': 18763,
 'linguistics': 21375,
 'doesn': 10738,
 'address': 1466,
 'racism': 29542,
 'raciolinguistics': 29541,
 'bringsã': 5803,
 'beloved': 4345,
 'cds': 6919,
 'recovered': 30015,
 'apple': 2720,
 'marvel': 22765,
 'song': 33628,
 'musica': 24384,
 'weed': 39274,
 'ripchristina': 30797,
 'adele': 1476,
 'vine': 38608,
 'why': 39731,
 'mocked': 23770,
 'brexit': 5730,
 'under': 37887,
 'spell': 33863,
 'referendum': 30108,
 'commerzbank': 8156,
 '100': 54,
 'health': 16691,
 'benefits': 4365,
 'cucumbers': 9170,
 'ofw': 26156,
 'pinoy': 27905,
 'followme': 13866,
 'igers': 17922,
 'instagood': 18625,
 'smile': 33272,
 'toradora': 36914,
 'anime': 2478,
 'animeedit': 2482,
 'breakups': 5685,
 'alone': 2123,
 'lonely': 21679,
 'laps': 20676,
 'pool': 28343,
 '10k': 97,
 'ride': 30711,
 'picked': 27788,
 'gym': 16134,
 'membership': 23138,
 'form': 14004,
 'cotd': 8713,
 'polar': 28249,
 'bear': 4050,
 'climb': 7769,
 'racing': 29540,
 'angry': 2443,
 'living': 21535,
 'cold': 7971,
 'places': 28003,
 'looking': 21737,
 'gets': 14988,
 'him': 17038,
 'muslim': 24416,
 'assassinating': 3036,
 'snappy': 33364,
 'waiting': 38872,
 'football': 13930,
 'fringes': 14308,
 'qcbags': 29360,
 'summer': 34835,
 'ã³â¾â': 41073,
 'nochebuena': 25490,
 'lasvegas': 20717,
 'usa': 38171,
 'las': 20689,
 'vegas': 38391,
 'strip': 34590,
 'ma': 22223,
 'fleurette': 13681,
 'instaboy': 18589,
 'instaman': 18654,
 'sefie': 32034,
 'septum': 32192,
 'friend': 14268,
 'blackandwhite': 4920,
 'branches': 5625,
 'rainy': 29635,
 'writing': 40314,
 'tears': 35737,
 'flying': 13796,
 'birds': 4853,
 'haiku': 16201,
 '3lines': 721,
 'micropoetry': 23371,
 'buttons': 6248,
 'mail': 22373,
 'me': 23003,
 'pretty': 28778,
 'jewelrymaking': 19452,
 'driver': 11149,
 'female': 13218,
 'moose': 23981,
 'river': 30855,
 'rd': 29819,
 'weston': 39466,
 'killed': 20171,
 'ok': 26208,
 'crews': 8999,
 'removing': 30331,
 'animal': 2458,
 'afterpas': 1669,
 'japan': 19295,
 'â¼â': 41050,
 'madeinjapan': 22277,
 'eos': 12116,
 'cute': 9278,
 'cawaii': 6877,
 'strawberry': 34516,
 'tomato': 36805,
 'aren': 2825,
 'protesting': 29052,
 'republican': 30418,
 'fuhered': 14421,
 'find': 13426,
 'spend': 33871,
 'guy': 16115,
 '1466047260': 203,
 'update': 38096,
 'analytics': 2364,
 'photooftheday': 27745,
 'likes': 21301,
 'anyone': 2634,
 'date': 9586,
 'doj': 10805,
 'fbi': 13061,
 'became': 4139,
 'corrupted': 8678,
 'emailgate': 11801,
 'hillary2016': 17022,
 'shameful': 32383,
 'disgraceful': 10520,
 'ridiculous': 30718,
 'stupidity': 34675,
 'makes': 22442,
 'than': 35980,
 'even': 12348,
 'negligence': 24937,
 'put': 29320,
 'sachintendulkar': 31338,
 'installation': 18647,
 'bihdayã': 4766,
 '21thbihday': 461,
 'bestfriend': 4469,
 'loveã': 22034,
 'most': 24052,
 'impoant': 18205,
 'thing': 36353,
 'matters': 22879,
 'too': 36853,
 'sho': 32585,
 'pooh4u': 28339,
 'chris': 7482,
 'evansã': 12341,
 'actor': 1421,
 'human': 17613,
 'â³ã': 41018,
 'chrisevans': 7484,
 'heas': 16734,
 'thoughts': 36452,
 'prayers': 28620,
 'murdered': 24357,
 'gay': 14763,
 'demoing': 9996,
 'guitars': 16058,
 'album': 1916,
 'newalbum': 25066,
 'indie': 18345,
 'echobelly': 11503,
 'retweeted': 30581,
 'lion': 21392,
 'pro': 28884,
 'webmareting': 39214,
 'seo': 32180,
 'community': 8186,
 'management': 22544,
 'nzd': 25993,
 'targets': 35526,
 'sma': 33218,
 '7190': 985,
 'bad': 3560,
 'worst': 40238,
 'ever': 12364,
 'bihdayweeksucks': 4762,
 'bithday27': 4891,
 'tã': 37693,
 'blessed': 5041,
 'worked': 40149,
 'sa': 31310,
 'leading': 20860,
 'ladiesã': 20546,
 'happiest': 16375,
 'eah': 11400,
 'disneysmagickingdom': 10560,
 'disney': 10549,
 'magickingdom': 22333,
 'disneyland': 10554,
 'orlandoã': 26615,
 'kinda': 20206,
 'among': 2316,
 'humans': 17622,
 'found': 14050,
 'exclaiming': 12478,
 'blain': 4995,
 'hair': 16205,
 'other': 26654,
 'nite': 25435,
 'lt': 22088,
 'listen': 21420,
 '17': 268,
 'freedom': 14163,
 'effo': 11636,
 'present': 28727,
 'merely': 23231,
 'stored': 34462,
 'past': 27194,
 'theodore': 36217,
 'rooseveltã': 31052,
 'yall': 40490,
 'aint': 1795,
 'commitment': 8161,
 'trust': 37396,
 'faithful': 12784,
 'michelleobama': 23356,
 'gorilla': 15582,
 'racists': 29545,
 'thought': 36445,
 'betã': 4558,
 'newarkfestival': 25068,
 '3rd': 727,
 'internet': 18787,
 'broken': 5870,
 'watch': 39063,
 'netflix': 25006,
 'mochithepug': 23768,
 'puglife': 29196,
 'then': 36208,
 'business': 6191,
 'usual': 38220,
 'hbd': 16617,
 'dick': 10302,
 'suckin': 34757,
 'tequila': 35863,
 'lovin': 22035,
 'slut': 33213,
 'wouldnt': 40251,
 'any': 2625,
 'justalillate': 19767,
 'butstillontime': 6234,
 'smaller': 33233,
 'hands': 16326,
 'barry': 3838,
 'probably': 28887,
 'lied': 21182,
 'game': 14645,
 'sucked': 34754,
 'golfã': 15411,
 'everyone': 12384,
 'doing': 10795,
 'goodmorning': 15492,
 'challenges': 7058,
 'claim': 7636,
 '70': 968,
 'punjabis': 29246,
 'drugaddicts': 11183,
 'dares': 9543,
 'tracerequest': 37022,
 'sending': 32148,
 'deepest': 9835,
 ...}

In [ ]:
#Idf of the terms   i.e weights assigned to the terms
tfidf_vect.idf_

array([ 7.44050863,  8.00503843, 10.27372197, ...,  9.42642411,
       10.67918708,  6.64494644])

# Decision Tree Algorithm

In [ ]:
test = pd.read_csv("/content/drive/My Drive/DS PROJECT/test.csv", encoding = 'Latin-1')
test

          id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid Ã°ÂÂÂ #hairflip #nev...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [ ]:
test.drop(['id'],axis = 1 ,inplace = True)
test

                                                   tweet
0      #studiolife #aislife #requires #passion #dedic...
1       @user #white #supremacists want everyone to s...
2      safe ways to heal your #acne!!    #altwaystohe...
3      is the hp and the cursed child book up for res...
4        3rd #bihday to my amazing, hilarious #nephew...
...                                                  ...
17192  thought factory: left-right polarisation! #tru...
17193  feeling like a mermaid Ã°ÂÂÂ #hairflip #nev...
17194  #hillary #campaigned today in #ohio((omg)) &am...
17195  happy, at work conference: right mindset leads...
17196  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 1 columns]

In [ ]:
#TFIDF Vectorizer

#Import TFIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
#Initialize an object for the TFIDF Vectorizer
tfidf_vect = TfidfVectorizer()

In [ ]:
#apply the tfidf to the data(X_train)
X_train_transformed = tfidf_vect.fit_transform(X_train)
X_train_transformed

<31962x41074 sparse matrix of type '<class 'numpy.float64'>'
	with 367513 stored elements in Compressed Sparse Row format>

In [ ]:
X_test_transformed = tfidf_vect.transform(test.tweet)
X_test_transformed

<17197x41074 sparse matrix of type '<class 'numpy.float64'>'
	with 183388 stored elements in Compressed Sparse Row format>

In [ ]:
result = pd.read_csv("/content/drive/My Drive/DS PROJECT/result.csv",encoding = 'Latin-1')
result

          id  label
0      31963      0
1      31964      0
2      31965      0
3      31966      0
4      31967      0
...      ...    ...
17192  49155      1
17193  49156      0
17194  49157      0
17195  49158      0
17196  49159      0

[17197 rows x 2 columns]

In [ ]:
result.drop(['id'],axis = 1,inplace = True)
result

       label
0          0
1          0
2          0
3          0
4          0
...      ...
17192      1
17193      0
17194      0
17195      0
17196      0

[17197 rows x 1 columns]

In [ ]:
# Apply the Decision Tree Algorithm
from sklearn.tree import DecisionTreeClassifier

#initailization of object
dtree = DecisionTreeClassifier()

# Applying the classifier to the dataset
# syntax: objectname.fit(InputValues, OutputValues)
dtree.fit(X_train_transformed, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
DecisionTreeClassifier()

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
# Predict on training data
y_train_pred = dtree.predict(X_train_transformed)
y_train_pred

array([0, 0, 0, ..., 0, 1, 0])

In [ ]:
# Classification Report on training data
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     29720
           1       1.00      1.00      1.00      2242

    accuracy                           1.00     31962
   macro avg       1.00      1.00      1.00     31962
weighted avg       1.00      1.00      1.00     31962

In [ ]:
confusion_matrix(y_train, y_train_pred)

array([[29720,     0],
       [    1,  2241]])

In [ ]:
# Prediction on test data(unseen data)
# Syntax: objectname.predict(InputValues)
y_test_pred =  dtree.predict(X_test_transformed)  #  corresponding output of X_test is stored in y_test
# Comapre the actual y_test values with model predicted y_test_pred values
print(classification_report(result.label, y_test_pred))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97     16282
           1       0.51      0.60      0.55       915

    accuracy                           0.95     17197
   macro avg       0.74      0.78      0.76     17197
weighted avg       0.95      0.95      0.95     17197

#Naive Bayes Algorithm

In [ ]:
##Apply the Naive Bayes Algorithm

#Import BerNB
from sklearn.naive_bayes import BernoulliNB

#Creating an object for BerNB
model_BernoulliNB = BernoulliNB()

In [ ]:
#Applying the Algorithm
model_BernoulliNB.fit(X_train_transformed,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
#Applying the Algorithm
model_BernoulliNB.fit(X_train_transformed,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [ ]:
#Prediction on Test Data
y_test_prediction = model_BernoulliNB.predict(X_test_transformed)
y_test_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#Compare the actual values y_test with predicted values y_test_pred
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(result.label,y_test_prediction)

array([[16234,    48],
       [  669,   246]])

In [ ]:
print(classification_report(result.label,y_test_prediction))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98     16282
           1       0.84      0.27      0.41       915

    accuracy                           0.96     17197
   macro avg       0.90      0.63      0.69     17197
weighted avg       0.95      0.96      0.95     17197